spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
  batch.job.enabled: false

feed-collector:
  cron: 0 0/1 * * * ?

elasticsearch:
  host: localhost
  port: 9200
  schema: http